# Copy this file to config.yml and adjust
config:
    # The base directory of the file browser
    rootdir: ~
    # The relative web path that points to the same location as the rootdir
    # Can be ignored if not displaying webpages
    webroot: ~
    webpageIndexFiles:
        - index.html
        - index.php
    directories:
        /:
            display:
                webpages: false
                directories: false
                files: false
            blacklist:
                webpages: []
                directories: []
                files: []
                all: []
            whitelist:
                webpages: []
                directories: []
                files: []
            recursive: true
            description: "Description"
        asdf/foo/:
            blacklist:
                all:
                - genericblacklist2
            recursive: true
        asdf/foo/bar/:
            display:
                files: true
            blacklist:
                webpages:
                - webpage3
            description: "Derp."
